from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.security import hash_password, utc_now
from app.db.session import SessionLocal
from app.modules.admin.models import AdminReview
from app.modules.market_suggestions.models import MarketSuggestion
from app.modules.markets.models import Category, Market, MarketRule, Outcome
from app.modules.market_issuance.models import DataSource
from app.modules.users.models import User, UserRole
from app.modules.wallets.service import get_or_create_wallet

CATEGORIES = [
  {
    "slug": "sports",
    "name": "Sports",
    "short_name": "Sports",
    "description": "Structured markets around matches, tournaments, milestones, and standings.",
    "active_markets": 48,
    "volume_24h": 12400000,
    "total_volume": 188000000,
    "risk": "MEDIUM",
    "icon_tone": "green",
    "focus_json": ["Cricket", "Football", "Tennis", "Tournaments"],
  },
  {
    "slug": "politics",
    "name": "Politics",
    "short_name": "Politics",
    "description": "Election, policy, appointment, and public decision markets with strict review.",
    "active_markets": 12,
    "volume_24h": 3200000,
    "total_volume": 91000000,
    "risk": "RESTRICTED",
    "icon_tone": "blue",
    "focus_json": ["Elections", "Policy", "Approval", "Appointments"],
  },
  {
    "slug": "economics",
    "name": "Economics",
    "short_name": "Economics",
    "description": "Macro releases, inflation, central bank decisions, and economic indicators.",
    "active_markets": 34,
    "volume_24h": 9600000,
    "total_volume": 142000000,
    "risk": "MEDIUM",
    "icon_tone": "brass",
    "focus_json": ["Inflation", "GDP", "Jobs", "Rates"],
  },
  {
    "slug": "stocks-mutual-funds",
    "name": "Stocks and mutual funds",
    "short_name": "Stocks",
    "description": "Price thresholds, NAV outcomes, corporate actions, and earnings milestones.",
    "active_markets": 20,
    "volume_24h": 7200000,
    "total_volume": 113000000,
    "risk": "RESTRICTED",
    "icon_tone": "green",
    "focus_json": ["Stocks", "Mutual funds", "NAV", "Earnings"],
  },
  {
    "slug": "financials",
    "name": "Financials",
    "short_name": "Financials",
    "description": "Rates, yields, FX, banking metrics, and financial index levels.",
    "active_markets": 26,
    "volume_24h": 8100000,
    "total_volume": 128000000,
    "risk": "HIGH",
    "icon_tone": "blue",
    "focus_json": ["FX", "Yields", "Rates", "Banks"],
  },
  {
    "slug": "weather-climate",
    "name": "Weather / climate",
    "short_name": "Weather",
    "description": "Temperature, rainfall, climate data releases, air quality, and storm outcomes.",
    "active_markets": 29,
    "volume_24h": 4100000,
    "total_volume": 68000000,
    "risk": "LOW",
    "icon_tone": "aqua",
    "focus_json": ["Temperature", "Rainfall", "AQI", "Storms"],
  },
  {
    "slug": "culture",
    "name": "Culture",
    "short_name": "Culture",
    "description": "Awards, box office, charts, streaming ranks, and public cultural events.",
    "active_markets": 18,
    "volume_24h": 2600000,
    "total_volume": 41000000,
    "risk": "MEDIUM",
    "icon_tone": "violet",
    "focus_json": ["Awards", "Box office", "Charts", "Streaming"],
  },
  {
    "slug": "tech-science",
    "name": "Tech and science",
    "short_name": "Tech",
    "description": "Launches, space missions, AI releases, research milestones, and approvals.",
    "active_markets": 31,
    "volume_24h": 6900000,
    "total_volume": 102000000,
    "risk": "MEDIUM",
    "icon_tone": "blue",
    "focus_json": ["AI", "Space", "Products", "Research"],
  },
  {
    "slug": "mentions",
    "name": "Mentions / public attention",
    "short_name": "Mentions",
    "description": "News, social, search, and ranking attention measured by approved providers.",
    "active_markets": 15,
    "volume_24h": 1900000,
    "total_volume": 36000000,
    "risk": "HIGH",
    "icon_tone": "red",
    "focus_json": ["News", "Search", "Social", "Rankings"],
  },
  {
    "slug": "commodities",
    "name": "Commodities",
    "short_name": "Commodities",
    "description": "Gold, oil, gas, agricultural products, inventory reports, and benchmarks.",
    "active_markets": 22,
    "volume_24h": 7800000,
    "total_volume": 119000000,
    "risk": "HIGH",
    "icon_tone": "brass",
    "focus_json": ["Gold", "Oil", "Gas", "Agriculture"],
  },
]

HISTORY_UP = [
  {"time": "2026-07-01", "value": 41, "volume": 1200},
  {"time": "2026-07-02", "value": 43, "volume": 1900},
  {"time": "2026-07-03", "value": 45, "volume": 2300},
  {"time": "2026-07-04", "value": 44, "volume": 1800},
  {"time": "2026-07-05", "value": 48, "volume": 3100},
  {"time": "2026-07-06", "value": 51, "volume": 4600},
  {"time": "2026-07-07", "value": 49, "volume": 3900},
  {"time": "2026-07-08", "value": 53, "volume": 5200},
  {"time": "2026-07-09", "value": 56, "volume": 6100},
]

MARKETS = [
  {
    "id": "ind-aus-final",
    "title": "Will India beat Australia in the next T20 final?",
    "category_slug": "sports",
    "subcategory": "Cricket",
    "market_type": "Binary",
    "status": "OPEN",
    "close_time": "Jul 18, 2026 18:30 IST",
    "source": "Official tournament result",
    "rule_summary": "YES resolves if India is declared match winner by the official tournament source.",
    "probability": 56,
    "change_24h": 3.8,
    "volume_24h": 2140000,
    "total_volume": 18800000,
    "liquidity": 3400000,
    "spread": 2.0,
    "traders": 1800,
    "risk_notes_json": ["Result must come from the official tournament source.", "Super over result counts if official source counts it."],
    "price_history_json": HISTORY_UP,
    "order_book_json": {
      "yes_bids": [{"price": 55, "quantity": 240}, {"price": 54, "quantity": 180}],
      "no_bids": [{"price": 43, "quantity": 210}, {"price": 42, "quantity": 120}],
    },
    "recent_trades_json": [{"time": "10:38", "outcome": "YES", "price": 56, "quantity": 24}],
    "outcomes": [{"label": "YES", "price": 56, "probability": 56}, {"label": "NO", "price": 44, "probability": 44}],
  },
  {
    "id": "cpi-above-4",
    "title": "Will the next CPI release be above 4.0 percent?",
    "category_slug": "economics",
    "subcategory": "Inflation",
    "market_type": "Threshold",
    "status": "OPEN",
    "close_time": "Aug 12, 2026 09:00 UTC",
    "source": "Official statistics release",
    "rule_summary": "YES resolves if the official headline CPI value is strictly above 4.0 percent.",
    "probability": 49,
    "change_24h": -2.1,
    "volume_24h": 1860000,
    "total_volume": 13200000,
    "liquidity": 2500000,
    "spread": 3.0,
    "traders": 920,
    "risk_notes_json": ["Initial official release counts unless corrected before settlement deadline."],
    "price_history_json": HISTORY_UP,
    "order_book_json": {"yes_bids": [{"price": 48, "quantity": 120}], "no_bids": [{"price": 50, "quantity": 110}]},
    "recent_trades_json": [{"time": "09:18", "outcome": "NO", "price": 50, "quantity": 30}],
    "outcomes": [{"label": "YES", "price": 49, "probability": 49}, {"label": "NO", "price": 51, "probability": 51}],
  },
  {
    "id": "gold-above-2500",
    "title": "Will gold settle above 2500 by month end?",
    "category_slug": "commodities",
    "subcategory": "Gold",
    "market_type": "Threshold",
    "status": "OPEN",
    "close_time": "Jul 31, 2026 21:00 UTC",
    "source": "Approved benchmark settlement price",
    "rule_summary": "YES resolves if the approved benchmark settlement price is above 2500.",
    "probability": 61,
    "change_24h": 1.4,
    "volume_24h": 1720000,
    "total_volume": 10100000,
    "liquidity": 1800000,
    "spread": 2.5,
    "traders": 760,
    "risk_notes_json": ["Settlement price differs from intraday spot price."],
    "price_history_json": HISTORY_UP,
    "order_book_json": {"yes_bids": [{"price": 60, "quantity": 190}], "no_bids": [{"price": 38, "quantity": 130}]},
    "recent_trades_json": [{"time": "09:52", "outcome": "YES", "price": 61, "quantity": 80}],
    "outcomes": [{"label": "YES", "price": 61, "probability": 61}, {"label": "NO", "price": 39, "probability": 39}],
  },
  {
    "id": "ai-model-release",
    "title": "Will a frontier AI lab release a new public model before October?",
    "category_slug": "tech-science",
    "subcategory": "AI",
    "market_type": "Conditional",
    "status": "OPEN",
    "close_time": "Sep 30, 2026 23:59 UTC",
    "source": "Official company announcement",
    "rule_summary": "YES resolves if an approved frontier lab publicly releases a qualifying model.",
    "probability": 64,
    "change_24h": 4.2,
    "volume_24h": 3100000,
    "total_volume": 16400000,
    "liquidity": 4200000,
    "spread": 2.0,
    "traders": 2200,
    "risk_notes_json": ["Rumors and leaks do not count."],
    "price_history_json": HISTORY_UP,
    "order_book_json": {"yes_bids": [{"price": 63, "quantity": 160}], "no_bids": [{"price": 35, "quantity": 100}]},
    "recent_trades_json": [{"time": "11:02", "outcome": "YES", "price": 64, "quantity": 12}],
    "outcomes": [{"label": "YES", "price": 64, "probability": 64}, {"label": "NO", "price": 36, "probability": 36}],
  },
  {
    "id": "bengaluru-rain-20mm",
    "title": "Will Bengaluru receive more than 20 mm rain tomorrow?",
    "category_slug": "weather-climate",
    "subcategory": "Rainfall",
    "market_type": "Binary",
    "status": "OPEN",
    "close_time": "Jul 10, 2026 00:00 IST",
    "source": "Approved weather station report",
    "rule_summary": "YES resolves if the approved station records more than 20 mm rainfall.",
    "probability": 42,
    "change_24h": -1.2,
    "volume_24h": 760000,
    "total_volume": 3200000,
    "liquidity": 980000,
    "spread": 4.0,
    "traders": 410,
    "risk_notes_json": ["Only the named station and measurement window count."],
    "price_history_json": HISTORY_UP,
    "order_book_json": {"yes_bids": [{"price": 41, "quantity": 90}], "no_bids": [{"price": 57, "quantity": 110}]},
    "recent_trades_json": [{"time": "08:44", "outcome": "NO", "price": 58, "quantity": 18}],
    "outcomes": [{"label": "YES", "price": 42, "probability": 42}, {"label": "NO", "price": 58, "probability": 58}],
  },
]

DATA_SOURCES = [
  {
    "name": "GDELT global news and events",
    "provider": "GDELT",
    "source_type": "NEWS_DISCOVERY",
    "category_slug": "mentions",
    "base_url": "https://www.gdeltproject.org/",
    "license_status": "DISCOVERY_ONLY",
    "automation_level": 1,
    "refresh_schedule": "INTRADAY",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "global news event candidates"},
    "notes": "Discovery and attention analytics only. Pair with official source before listing settlement-sensitive markets.",
  },
  {
    "name": "NewsAPI everything and top headlines",
    "provider": "NewsAPI",
    "source_type": "NEWS_DISCOVERY",
    "category_slug": "culture",
    "base_url": "https://newsapi.org/docs",
    "license_status": "DISCOVERY_ONLY",
    "automation_level": 1,
    "refresh_schedule": "INTRADAY",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "culture entertainment award announcements"},
    "notes": "Discovery only. News articles do not settle markets unless the rule explicitly names an approved source.",
  },
  {
    "name": "Official RSS feeds",
    "provider": "RSS",
    "source_type": "RSS_DISCOVERY",
    "category_slug": "tech-science",
    "base_url": "https://www.rssboard.org/rss-specification",
    "license_status": "PUBLIC_STANDARD",
    "automation_level": 1,
    "refresh_schedule": "INTRADAY",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "official company agency journal RSS feeds"},
    "notes": "Use for official-source discovery and evidence capture; settlement eligibility depends on the publisher.",
  },
  {
    "name": "ICC official fixtures and results",
    "provider": "ICC",
    "source_type": "OFFICIAL",
    "category_slug": "sports",
    "base_url": "https://www.icc-cricket.com/fixtures-results",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "DAILY",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "international cricket fixtures and results"},
    "notes": "Official cricket result source for settlement examples.",
  },
  {
    "name": "Sportradar sports APIs",
    "provider": "Sportradar",
    "source_type": "LICENSED_API",
    "category_slug": "sports",
    "base_url": "https://developer.sportradar.com/getting-started/docs/get-started",
    "license_status": "LICENSE_REQUIRED",
    "automation_level": 1,
    "refresh_schedule": "LIVE_OR_VENDOR",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "licensed sports schedules scores standings"},
    "notes": "Enterprise vendor option. Mark settlement eligible only after contract and coverage review.",
  },
  {
    "name": "Football-Data.org",
    "provider": "Football-Data.org",
    "source_type": "SPORTS_API",
    "category_slug": "sports",
    "base_url": "https://www.football-data.org/documentation/api",
    "license_status": "REVIEW_REQUIRED",
    "automation_level": 1,
    "refresh_schedule": "HOURLY",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "football fixtures results standings"},
    "notes": "Good football discovery/prototype source; settlement requires source and license review.",
  },
  {
    "name": "Cricsheet cricket data",
    "provider": "Cricsheet",
    "source_type": "OPEN_DATA",
    "category_slug": "sports",
    "base_url": "https://cricsheet.org/",
    "license_status": "OPEN_DATA",
    "automation_level": 1,
    "refresh_schedule": "DAILY",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "cricket historical structured data"},
    "notes": "Strong analytics/backtesting source. Do not use as sole settlement source over official result pages.",
  },
  {
    "name": "FRED economic data",
    "provider": "FRED",
    "source_type": "OFFICIAL_API",
    "category_slug": "economics",
    "base_url": "https://fred.stlouisfed.org/docs/api/fred/series_observations.html",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "RELEASE_CALENDAR",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "official macroeconomic release calendar"},
    "notes": "Official economic series API used for US macro examples.",
  },
  {
    "name": "BLS public data API",
    "provider": "BLS",
    "source_type": "OFFICIAL_API",
    "category_slug": "economics",
    "base_url": "https://www.bls.gov/developers/home.htm",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "RELEASE_CALENDAR",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "CPI unemployment jobs wages inflation"},
    "notes": "Official US labor and inflation source.",
  },
  {
    "name": "BEA economic data API",
    "provider": "BEA",
    "source_type": "OFFICIAL_API",
    "category_slug": "economics",
    "base_url": "https://apps.bea.gov/api/signup/",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "RELEASE_CALENDAR",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "GDP NIPA official economic statistics"},
    "notes": "Official US GDP and national accounts source; API key required.",
  },
  {
    "name": "World Bank Indicators API",
    "provider": "World Bank",
    "source_type": "OFFICIAL_API",
    "category_slug": "economics",
    "base_url": "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "MONTHLY_OR_ANNUAL",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "global macro indicators"},
    "notes": "Global macro source. Watch release timing and revision policy.",
  },
  {
    "name": "FEC OpenFEC API",
    "provider": "FEC",
    "source_type": "OFFICIAL_API",
    "category_slug": "politics",
    "base_url": "https://api.open.fec.gov/developers/",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 0,
    "refresh_schedule": "MANUAL_REVIEW",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "federal campaign finance filings"},
    "notes": "Politics remains manual/admin-first pending jurisdiction and legal review.",
  },
  {
    "name": "Official election authority source",
    "provider": "Government election authority",
    "source_type": "OFFICIAL",
    "category_slug": "politics",
    "base_url": "https://www.usa.gov/election-office",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 0,
    "refresh_schedule": "MANUAL_REVIEW",
    "settlement_eligible": True,
    "discovery_eligible": False,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "official certified election results"},
    "notes": "Placeholder for jurisdiction-specific election offices. Configure exact source per market.",
  },
  {
    "name": "SEC EDGAR APIs",
    "provider": "SEC",
    "source_type": "OFFICIAL_API",
    "category_slug": "stocks-mutual-funds",
    "base_url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "INTRADAY",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "corporate filings and disclosure events"},
    "notes": "Filings source only; price and NAV markets need market-data/NAV source review.",
  },
  {
    "name": "Finnhub financial APIs",
    "provider": "Finnhub",
    "source_type": "MARKET_DATA_API",
    "category_slug": "stocks-mutual-funds",
    "base_url": "https://finnhub.io/docs/api",
    "license_status": "LICENSE_REQUIRED",
    "automation_level": 1,
    "refresh_schedule": "LIVE_OR_VENDOR",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "earnings market data company news fundamentals"},
    "notes": "Use for discovery/prototype until licensing and redistribution rights are approved.",
  },
  {
    "name": "Alpha Vantage market and economic data",
    "provider": "Alpha Vantage",
    "source_type": "MARKET_DATA_API",
    "category_slug": "financials",
    "base_url": "https://www.alphavantage.co/documentation/",
    "license_status": "LICENSE_REQUIRED",
    "automation_level": 1,
    "refresh_schedule": "VENDOR_LIMITED",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "forex yields indicators commodities stock market data"},
    "notes": "Useful for prototype discovery and analytics. Settlement requires license review.",
  },
  {
    "name": "Nasdaq Data Link",
    "provider": "Nasdaq",
    "source_type": "MARKET_DATA_API",
    "category_slug": "financials",
    "base_url": "https://docs.data.nasdaq.com/",
    "license_status": "LICENSE_REQUIRED",
    "automation_level": 1,
    "refresh_schedule": "VENDOR_LIMITED",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "financial market datasets reference data"},
    "notes": "Candidate licensed vendor for financial/index/reference data.",
  },
  {
    "name": "NOAA National Weather Service API",
    "provider": "NOAA",
    "source_type": "OFFICIAL_API",
    "category_slug": "weather-climate",
    "base_url": "https://www.weather.gov/documentation/services-web-api",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "HOURLY",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "official weather observations and alerts"},
    "notes": "Official US weather API; local country agencies should be configured separately.",
  },
  {
    "name": "NOAA NCEI climate data services",
    "provider": "NOAA NCEI",
    "source_type": "OFFICIAL_API",
    "category_slug": "weather-climate",
    "base_url": "https://www.ncei.noaa.gov/support/access-data-service-api-user-documentation",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "DAILY",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "climate station historical observations"},
    "notes": "Official climate observations and historical data source.",
  },
  {
    "name": "Open-Meteo forecast and historical APIs",
    "provider": "Open-Meteo",
    "source_type": "WEATHER_API",
    "category_slug": "weather-climate",
    "base_url": "https://open-meteo.com/en/docs",
    "license_status": "DISCOVERY_ONLY",
    "automation_level": 1,
    "refresh_schedule": "HOURLY",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "weather forecasts historical reanalysis"},
    "notes": "Excellent discovery/prototype source; use official station/source for settlement.",
  },
  {
    "name": "TMDb API",
    "provider": "TMDb",
    "source_type": "CULTURE_API",
    "category_slug": "culture",
    "base_url": "https://developer.themoviedb.org/docs/getting-started",
    "license_status": "REVIEW_REQUIRED",
    "automation_level": 1,
    "refresh_schedule": "DAILY",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "movies TV entertainment metadata"},
    "notes": "Culture discovery and identity metadata; box-office/award settlement needs official source.",
  },
  {
    "name": "MusicBrainz API",
    "provider": "MusicBrainz",
    "source_type": "OPEN_DATA_API",
    "category_slug": "culture",
    "base_url": "https://musicbrainz.org/doc/MusicBrainz_API",
    "license_status": "OPEN_DATA",
    "automation_level": 1,
    "refresh_schedule": "DAILY",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "music artist release metadata"},
    "notes": "Good metadata source; chart markets need official chart or licensed chart provider.",
  },
  {
    "name": "Official company announcement feeds",
    "provider": "Company/agency/journal",
    "source_type": "OFFICIAL",
    "category_slug": "tech-science",
    "base_url": "https://example.com/official-announcements",
    "license_status": "REVIEW_REQUIRED",
    "automation_level": 1,
    "refresh_schedule": "RSS_OR_MANUAL",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "official product launch science publication agency announcement"},
    "notes": "Template source. Replace with exact official company, journal, agency, or regulator endpoint per market.",
  },
  {
    "name": "Wikimedia Analytics API",
    "provider": "Wikimedia",
    "source_type": "ATTENTION_API",
    "category_slug": "mentions",
    "base_url": "https://doc.wikimedia.org/generated-data-platform/aqs/analytics-api/reference/page-views.html",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "DAILY",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "wikipedia pageview thresholds"},
    "notes": "Good public-attention source when market specifies exact page, project, access type, and window.",
  },
  {
    "name": "Google Trends API alpha",
    "provider": "Google",
    "source_type": "ATTENTION_API",
    "category_slug": "mentions",
    "base_url": "https://developers.google.com/search/apis/trends",
    "license_status": "ACCESS_RESTRICTED",
    "automation_level": 1,
    "refresh_schedule": "VENDOR_LIMITED",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "search interest trends attention markets"},
    "notes": "Official API is alpha/restricted. Do not use unofficial scraping for settlement.",
  },
  {
    "name": "EIA open energy data",
    "provider": "EIA",
    "source_type": "OFFICIAL_API",
    "category_slug": "commodities",
    "base_url": "https://www.eia.gov/opendata/",
    "license_status": "PUBLIC_OFFICIAL",
    "automation_level": 1,
    "refresh_schedule": "WEEKLY",
    "settlement_eligible": True,
    "discovery_eligible": True,
    "status": "ACTIVE",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "energy inventory and benchmark data"},
    "notes": "Official US energy data; price-settled commodity markets still need exchange/vendor review.",
  },
  {
    "name": "CME Group market data APIs",
    "provider": "CME Group",
    "source_type": "EXCHANGE_DATA_API",
    "category_slug": "commodities",
    "base_url": "https://www.cmegroup.com/market-data/market-data-api.html",
    "license_status": "LICENSE_REQUIRED",
    "automation_level": 1,
    "refresh_schedule": "EXCHANGE_CALENDAR",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "commodity futures settlement prices"},
    "notes": "Potential settlement source after data contract, redistribution, and benchmark rules are approved.",
  },
  {
    "name": "Alpha Vantage commodities data",
    "provider": "Alpha Vantage",
    "source_type": "MARKET_DATA_API",
    "category_slug": "commodities",
    "base_url": "https://www.alphavantage.co/documentation/",
    "license_status": "LICENSE_REQUIRED",
    "automation_level": 1,
    "refresh_schedule": "VENDOR_LIMITED",
    "settlement_eligible": False,
    "discovery_eligible": True,
    "status": "REVIEW_REQUIRED",
    "health_status": "UNKNOWN",
    "config_json": {"default_query": "commodities price index energy metals"},
    "notes": "Discovery/prototype source for commodity analytics; settlement requires licensed benchmark approval.",
  },
]


def seed_users(db: Session) -> None:
  users = [
    ("trader@predmarket.dev", "Demo Trader", ["USER"]),
    ("admin@predmarket.dev", "Demo Admin", ["USER", "ADMIN", "CHECKER", "MARKET_CREATOR"]),
    ("checker@predmarket.dev", "Demo Checker", ["USER", "ADMIN", "CHECKER"]),
  ]
  for email, display_name, roles in users:
    user = db.scalar(select(User).where(User.email == email))
    if not user:
      user = User(
        email=email,
        display_name=display_name,
        password_hash=hash_password("StrongPass123"),
        email_verified_at=utc_now(),
      )
      db.add(user)
      db.flush()
    existing_roles = {role.role for role in user.roles}
    for role in roles:
      if role not in existing_roles:
        user.roles.append(UserRole(role=role, created_at=utc_now()))
    get_or_create_wallet(db, user.id)


def seed_categories(db: Session) -> None:
  for payload in CATEGORIES:
    category = db.get(Category, payload["slug"])
    if category:
      for key, value in payload.items():
        setattr(category, key, value)
    else:
      db.add(Category(**payload))


def seed_markets(db: Session) -> None:
  for source_payload in MARKETS:
    payload = dict(source_payload)
    outcomes = payload.pop("outcomes")
    market = db.get(Market, payload["id"])
    if market:
      for key, value in payload.items():
        setattr(market, key, value)
    else:
      market = Market(**payload)
      db.add(market)
      db.flush()
      db.add(
        MarketRule(
          market_id=market.id,
          resolution_rule=market.rule_summary,
          void_policy="Void only if approved source is unavailable or event is cancelled under category rulebook.",
          source_url=None,
        )
      )
    existing_outcomes = {outcome.label: outcome for outcome in market.outcomes}
    for outcome_payload in outcomes:
      existing = existing_outcomes.get(outcome_payload["label"])
      if existing:
        existing.price = outcome_payload["price"]
        existing.probability = outcome_payload["probability"]
      else:
        market.outcomes.append(Outcome(**outcome_payload))


def seed_data_sources(db: Session) -> None:
  for payload in DATA_SOURCES:
    source = db.scalar(select(DataSource).where(DataSource.name == payload["name"], DataSource.provider == payload["provider"]))
    if source:
      for key, value in payload.items():
        setattr(source, key, value)
    else:
      db.add(DataSource(**payload))


def seed_admin_reviews(db: Session) -> None:
  if db.scalar(select(AdminReview.id).limit(1)):
    return
  db.add_all(
    [
      AdminReview(title="Will Bengaluru receive more than 20 mm rain tomorrow?", category="Weather / climate", status="Source check", risk="LOW", submitted_by="user_1829"),
      AdminReview(title="Will the next policy rate decision be a hold?", category="Economics", status="Resolution review", risk="MEDIUM", submitted_by="user_1041"),
      AdminReview(title="Will a listed stock close above its 52-week high?", category="Stocks and mutual funds", status="Legal review", risk="RESTRICTED", submitted_by="user_2810"),
    ]
  )


def seed_database(db: Session) -> None:
  seed_users(db)
  seed_categories(db)
  seed_markets(db)
  seed_data_sources(db)
  seed_admin_reviews(db)
  db.commit()


def main() -> None:
  with SessionLocal() as db:
    seed_database(db)


if __name__ == "__main__":
  main()
